import type { ExpoConfig } from 'expo/config';

// Single source of native configuration (spec §2.3). ios/ and android/ are
// generated by `expo prebuild` from this file and are not committed.
const config: ExpoConfig = {
  name: 'YourIntelliLedger',
  slug: 'yourintelliledger',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './assets/images/icon.png',
  scheme: 'yourintelliledger',
  userInterfaceStyle: 'automatic',
  android: {
    package: 'nz.yourintelliledger.app',
    allowBackup: false, // §8.2 [A] — otherwise the ledger DB is silently
                        // synced to Google's auto-backup
    permissions: ['CAMERA'],
    adaptiveIcon: {
      // Sampled from the artwork's night sky, so the mask's edge blends with
      // the image rather than showing a contrasting ring.
      backgroundColor: '#11235F',
      foregroundImage: './assets/images/android-icon-foreground.png',
      // No backgroundImage or monochromeImage: the template's were unrelated
      // artwork, and a themed (monochrome) icon derived automatically from a
      // full-colour illustration reads as a smudge. Android falls back to the
      // standard icon for themed mode, which is the better of the two.
    },
    predictiveBackGestureEnabled: false,
  },
  ios: {
    bundleIdentifier: 'nz.yourintelliledger.app',
    supportsTablet: false,
    // No `icon` override: the template pointed this at its own `expo.icon`
    // asset catalog, which would have silently kept the Expo logo on iOS no
    // matter what the top-level `icon` said.
    infoPlist: {
      NSCameraUsageDescription:
        'Used to photograph receipts so purchases can be recorded automatically.',
      NSPhotoLibraryUsageDescription:
        'Used to import a receipt photo you have already taken.',
    },
  },
  // No `web` block: the spec targets Android and iOS only (§0), and a third
  // render target would legitimise `.web.tsx` forks that §2.2 rule 3 exists
  // to prevent.
  plugins: [
    'expo-router',
    [
      'expo-splash-screen',
      {
        // The launch screen this hands over to (src/ui/components/launch-screen.tsx)
        // draws the same mark at the same size on a gradient whose middle stop
        // is this colour, so the handoff is invisible. Changing one without the
        // other puts a visible cut in the first second of every launch.
        //
        // Dark mode gets no variant: the artwork is a night scene, so the
        // launch sequence is deliberately dark in both schemes.
        backgroundColor: '#11235F',
        image: './assets/images/splash-icon.png',
        imageWidth: 132,
      },
    ],
    'expo-sqlite',
    'expo-secure-store',
    'expo-camera',
    'expo-image-picker',
    'react-native-document-scanner-plugin',
    // NOT @react-native-ml-kit/text-recognition or /barcode-scanning: neither
    // ships an app.plugin.js (verified against the installed packages) — they
    // autolink via the RN CLI + CocoaPods instead. Listing a plugin-less
    // package here breaks `expo prebuild`'s plugin resolution. The spec's
    // §2.3 example listed text-recognition here; corrected in spec v2.10.
    //
    // Note: a local plugin CANNOT fix "Exec failed, error: 2" (node not found)
    // for a Dock-launched Android Studio. Patching the generated Gradle files
    // covers only 7 of the 9 call sites; `expo-autolinking-settings` hardcodes
    // "node" in Kotlin with no property or env override. `node` must be on the
    // PATH the IDE inherits — see README, "Android Studio".

    // Local plugin (§2.3): R8 + resource shrinking for release builds, and the
    // §1.1 ABI list. android/gradle.properties is generated and gitignored, so
    // these cannot live there.
    './plugins/with-android-build-props',

    // Local plugin (§2.3): the Apple development team, which ios/ would
    // otherwise lose on every regenerate. Override with APPLE_TEAM_ID.
    './plugins/with-ios-signing',
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
};

export default config;
