import type { ExpoConfig } from 'expo/config';

// Single source of native configuration (spec §2.3). ios/ and android/ are
// generated by `expo prebuild` from this file and are not committed.
const config: ExpoConfig = {
  name: 'YourIntelliLedger',
  slug: 'yourintelliledger',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './assets/images/icon.png',
  scheme: 'yourintelliledger',
  userInterfaceStyle: 'automatic',
  android: {
    package: 'nz.yourintelliledger.app',
    allowBackup: false, // §8.2 [A] — otherwise the ledger DB is silently
                        // synced to Google's auto-backup
    permissions: ['CAMERA'],
    adaptiveIcon: {
      backgroundColor: '#E6F4FE',
      foregroundImage: './assets/images/android-icon-foreground.png',
      backgroundImage: './assets/images/android-icon-background.png',
      monochromeImage: './assets/images/android-icon-monochrome.png',
    },
    predictiveBackGestureEnabled: false,
  },
  ios: {
    bundleIdentifier: 'nz.yourintelliledger.app',
    supportsTablet: false,
    icon: './assets/expo.icon',
    infoPlist: {
      NSCameraUsageDescription:
        'Used to photograph receipts so purchases can be recorded automatically.',
      NSPhotoLibraryUsageDescription:
        'Used to import a receipt photo you have already taken.',
    },
  },
  // No `web` block: the spec targets Android and iOS only (§0), and a third
  // render target would legitimise `.web.tsx` forks that §2.2 rule 3 exists
  // to prevent.
  plugins: [
    'expo-router',
    [
      'expo-splash-screen',
      {
        backgroundColor: '#208AEF',
        image: './assets/images/splash-icon.png',
        imageWidth: 76,
      },
    ],
    'expo-sqlite',
    'expo-secure-store',
    'expo-camera',
    'react-native-document-scanner-plugin',
    // NOT @react-native-ml-kit/text-recognition or /barcode-scanning: neither
    // ships an app.plugin.js (verified against the installed packages) — they
    // autolink via the RN CLI + CocoaPods instead. Listing a plugin-less
    // package here breaks `expo prebuild`'s plugin resolution. The spec's
    // §2.3 example listed text-recognition here; corrected in spec v2.10.
    //
    // Note: a local plugin CANNOT fix "Exec failed, error: 2" (node not found)
    // for a Dock-launched Android Studio. Patching the generated Gradle files
    // covers only 7 of the 9 call sites; `expo-autolinking-settings` hardcodes
    // "node" in Kotlin with no property or env override. `node` must be on the
    // PATH the IDE inherits — see README, "Android Studio".
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
};

export default config;
