#!/usr/bin/env node
/**
 * Runs a command with JAVA_HOME pinned to JDK 17.
 *
 * Spec §1.1 / §12 item 1: the Android build JDK is a hard requirement, not a
 * preference. Under JDK 26 (a common machine default) the current AGP fails
 * outright in the `jlink`/`androidJdkImage` transform against android-36's
 * `core-for-system-modules.jar`, and it takes `react-native-svg` and
 * `react-native-masked-view` down with it — a failure that reads like a
 * New Architecture problem but isn't.
 *
 * `android/` is generated by `expo prebuild` and gitignored, so the pin
 * cannot live in `gradle.properties`. It lives here instead, which also
 * makes it work identically in CI.
 */

const { execFileSync, spawn, spawnSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const REQUIRED_MAJOR = 17;

/** Reads the major version JDK at `home` reports, or null if it isn't usable. */
function majorVersionOf(home) {
  const javaBin = path.join(home, 'bin', 'java');
  if (!fs.existsSync(javaBin)) return null;
  // `java -version` writes to stderr on every JDK ever shipped, so both
  // streams have to be read — stdout alone is empty.
  const result = spawnSync(javaBin, ['-version'], { encoding: 'utf8' });
  return parseMajor(`${result.stderr ?? ''}${result.stdout ?? ''}`);
}

function parseMajor(text) {
  const match = /version "(\d+)(?:\.(\d+))?/.exec(text);
  if (!match) return null;
  const first = Number(match[1]);
  // Pre-9 JDKs report as 1.8.x; everything since reports the major directly.
  return first === 1 ? Number(match[2]) : first;
}

function candidateHomes() {
  const candidates = [];

  // GitHub Actions' setup-java exports these.
  for (const key of Object.keys(process.env)) {
    if (/^JAVA_HOME_17(_|$)/.test(key) && process.env[key]) candidates.push(process.env[key]);
  }

  if (process.platform === 'darwin') {
    try {
      candidates.push(
        execFileSync('/usr/libexec/java_home', ['-v', String(REQUIRED_MAJOR)], {
          encoding: 'utf8',
          stdio: ['ignore', 'pipe', 'ignore'],
        }).trim()
      );
    } catch {
      // java_home exits non-zero when no matching JDK is installed.
    }
  }

  for (const dir of ['/usr/lib/jvm', '/Library/Java/JavaVirtualMachines']) {
    if (!fs.existsSync(dir)) continue;
    for (const entry of fs.readdirSync(dir)) {
      candidates.push(path.join(dir, entry, 'Contents', 'Home'), path.join(dir, entry));
    }
  }

  if (process.env.JAVA_HOME) candidates.push(process.env.JAVA_HOME);

  return candidates.filter((home) => home && fs.existsSync(home));
}

function resolveJdk17() {
  for (const home of candidateHomes()) {
    if (majorVersionOf(home) === REQUIRED_MAJOR) return home;
  }
  return null;
}

const [command, ...args] = process.argv.slice(2);
if (!command) {
  console.error('usage: with-jdk17.js <command> [args...]');
  process.exit(2);
}

const javaHome = resolveJdk17();
if (!javaHome) {
  console.error(
    `\nCannot find JDK ${REQUIRED_MAJOR}, which the Android build requires (spec §1.1).\n` +
      `Whatever JDK is newest will not do — JDK 26 fails the AGP jlink step outright.\n\n` +
      `  macOS:  brew install --cask temurin@17\n` +
      `  Linux:  apt install temurin-17-jdk  (or your distro's equivalent)\n` +
      `  CI:     actions/setup-java with java-version 17\n`
  );
  process.exit(1);
}

console.log(`[with-jdk17] JAVA_HOME=${javaHome}`);

const child = spawn(command, args, {
  stdio: 'inherit',
  shell: process.platform === 'win32',
  env: { ...process.env, JAVA_HOME: javaHome, PATH: `${path.join(javaHome, 'bin')}:${process.env.PATH}` },
});

child.on('exit', (code, signal) => {
  if (signal) process.kill(process.pid, signal);
  else process.exit(code ?? 0);
});
