/**
 * Development seed: the eleven real receipts parsed by the Python prototype.
 *
 * The fixture is generated by `scripts/build-receipt-corpus.js` from
 * `../PyPrototype/out`, and committed so the seed does not depend on a sibling
 * repository being present. It doubles as §10's receipt corpus — saved OCR
 * text plus expected JSON — which Weeks 5–6 need for line reconstruction and
 * re-parse work.
 *
 * Seeding goes through `createBill`, not raw SQL, so `merchant_norm` (§4.8) and
 * the §4.11 integrity flags are derived exactly as they would be in production.
 * Seeded data that skipped those would be worse than no data: it would look
 * real while behaving differently from anything a user could produce.
 *
 * **This is a development affordance, not a feature.** The user-facing import
 * lands in Week 9 (§15.1); callers gate on `__DEV__`.
 */

import corpusJson from '@/assets/receipts/corpus.json';
import type { SqlDriver } from '@/data/driver';
import { createBill, deleteAllBills, replaceReceiptScans } from '@/data/ledgerRepo';
import type { NewBillInput } from '@/types/ledger';
import type { Category, Confidence, Unit } from '@/types/vocabulary';

interface CorpusItem {
  name: string;
  nameLocal: string | null;
  category: string;
  isFood: boolean;
  qty: number;
  unit: string;
  scanUnits: number;
  priceCents: number | null;
  unitPriceCents: number | null;
  barcode: string | null;
  confidence: string | null;
}

interface CorpusBill {
  slug: string;
  merchant: string | null;
  merchantAddress: string | null;
  purchasedAt: string;
  purchasedTime: string | null;
  totalCents: number | null;
  discountCents: number;
  currency: string;
  unitsSold: number | null;
  source: string;
  capturePath: string;
  modelAlias: string | null;
  items: CorpusItem[];
  pages: { pageNo: number; ocrText: string }[];
}

interface Corpus {
  schema_version: number;
  exported_at: string;
  source: string;
  bills: CorpusBill[];
}

export const CORPUS = corpusJson as Corpus;

export interface SeedResult {
  deleted: number;
  billsInserted: number;
  itemsInserted: number;
  pagesInserted: number;
}

export interface SeedOptions {
  /** Delete every existing bill first. Irreversible; callers confirm. */
  replaceExisting?: boolean;
}

/**
 * Loads the corpus into the database.
 *
 * Each bill is its own transaction (inside `createBill`) rather than one giant
 * one: a single malformed record should not cost the other ten, and this
 * mirrors how bills actually arrive — one capture at a time.
 */
export async function seedCorpus(
  db: SqlDriver,
  options: SeedOptions = {}
): Promise<SeedResult> {
  const deleted = options.replaceExisting ? await deleteAllBills(db) : 0;

  let billsInserted = 0;
  let itemsInserted = 0;
  let pagesInserted = 0;

  for (const bill of CORPUS.bills) {
    const billId = await createBill(db, toNewBillInput(bill));
    billsInserted += 1;
    itemsInserted += bill.items.length;

    const pages = bill.pages.map((page) => page.ocrText);
    if (pages.length > 0) {
      await replaceReceiptScans(db, billId, pages);
      pagesInserted += pages.length;
    }
  }

  return { deleted, billsInserted, itemsInserted, pagesInserted };
}

function toNewBillInput(bill: CorpusBill): NewBillInput {
  return {
    merchant: bill.merchant,
    merchantAddress: bill.merchantAddress,
    purchasedAt: bill.purchasedAt,
    purchasedTime: bill.purchasedTime,
    totalCents: bill.totalCents,
    discountCents: bill.discountCents,
    currency: bill.currency,
    unitsSold: bill.unitsSold,
    source: 'receipt',
    capturePath: 'gallery',
    modelAlias: bill.modelAlias,
    items: bill.items.map((item) => ({
      name: item.name,
      nameLocal: item.nameLocal,
      category: item.category as Category,
      isFood: item.isFood,
      qty: item.qty,
      unit: item.unit as Unit,
      scanUnits: item.scanUnits,
      priceCents: item.priceCents,
      unitPriceCents: item.unitPriceCents,
      barcode: item.barcode,
      confidence: item.confidence as Confidence | null,
    })),
  };
}
